name: Construir y Subir Imagen Docker a DigitalOcean

on:
  push:
    branches:
      - main # O la rama que uses para producción

env:
  # REEMPLAZA 'twosix-registry' CON EL NOMBRE DE TU REGISTRY EN DIGITALOCEAN
  REGISTRY: registry.digitalocean.com/twosix-registry
  IMAGE_NAME: two-six-web

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Instalar doctl (DigitalOcean CLI)
        uses: digitalocean/action-doctl@v2
        with:
          # TOKEN CREADO EN DIGITAL OCEAN Y GUARDADO EN GITHUB SECRETS
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: 3. Autenticarse en el Container Registry de DO
        run: doctl registry login --expiry-seconds 3600

      - name: 4. Borrar tags antiguos para liberar espacio (Previene Quota Exceeded)
        run: |
          doctl registry repository list-manifests ${{ env.IMAGE_NAME }} --format Digest,Tags --no-header | grep -v "latest" | awk '{print $1}' | xargs -I {} doctl registry repository delete-manifest ${{ env.IMAGE_NAME }} {} --force || true

      - name: 5. Construir la Imagen (Docker Build) usando la RAM de GitHub
        run: docker build --build-arg NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: 6. Subir imagen al Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
